# Generated by Django 3.2.8 on 2021-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20211105_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='姓名')),
                ('voter', models.ManyToManyField(to='login.User', verbose_name='投票人')),
            ],
        ),
    ]
