# Generated by Django 3.2.8 on 2021-11-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('independentPoll', '0002_auto_20211105_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderpolldatamodel',
            name='pollGrade',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], default='合格', max_length=64, verbose_name='评价等级'),
        ),
    ]
