# Generated by Django 3.2.8 on 2021-11-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentPoll', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_poll', models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=128, verbose_name='是否已经打分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_kogin_time', models.DateTimeField(auto_now=True, verbose_name='最后一次登陆时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentPoll.workgroup', verbose_name='组别')),
            ],
        ),
        migrations.CreateModel(
            name='PollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='德')),
                ('question2', models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='能')),
                ('question3', models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='勤')),
                ('question4', models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='绩')),
                ('question5', models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='廉')),
                ('reason', models.CharField(blank=True, default='', max_length=2048, verbose_name='评价理由')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentPoll.workgroup', verbose_name='组别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='用户')),
            ],
        ),
    ]
