# Generated by Django 3.2.8 on 2021-11-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentPoll', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollData',
            new_name='DepartmentPollData',
        ),
    ]
