# Generated by Django 3.2.8 on 2021-10-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        ('login', '0002_user_is_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.workgroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_poll',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=128, verbose_name='是否已经打分'),
        ),
    ]
