# Generated by Django 3.2.8 on 2021-11-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211105_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_poll',
        ),
        migrations.AddField(
            model_name='user',
            name='is_poll_1',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=128, verbose_name='是否已经打分(部门)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_poll_2',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=128, verbose_name='是否已经打分(领导)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_poll_3',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=128, verbose_name='是否已经打分(部门独立)'),
        ),
    ]
