# Generated by Django 3.2.8 on 2021-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211020_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldata',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='评价理由'),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='question1',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='德'),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='question2',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='能'),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='question3',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='勤'),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='question4',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='绩'),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='question5',
            field=models.CharField(choices=[('优秀', '优秀'), ('合格', '合格'), ('基本合格', '基本合格'), ('不合格', '不合格')], max_length=16, verbose_name='廉'),
        ),
    ]
