# Generated by Django 3.2.8 on 2021-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=256, verbose_name='分组名称')),
                ('groupDirector', models.CharField(max_length=256, verbose_name='分组主管')),
            ],
        ),
    ]
