# Generated by Django 3.2.8 on 2021-11-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentPoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={'verbose_name': '部门组别', 'verbose_name_plural': '部门组别'},
        ),
    ]
