# Generated by Django 3.2.8 on 2021-10-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='question1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question2',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question3',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question4',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question5',
            field=models.CharField(default='', max_length=512),
        ),
    ]
