# Generated by Django 3.2.8 on 2021-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20211010_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='question10',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question6',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question7',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question8',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='question9',
            field=models.CharField(default='', max_length=512),
        ),
    ]
