# Generated by Django 3.2.8 on 2021-10-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20211010_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='question9',
        ),
    ]
